### ISSUE TITLE
Cannot tap both Eye and Sound buttons simultaneously on Android

### ISSUE THREAD

**Issue by NateEag** [jperryhouts/Dual-N-Back#1]
If I tap both buttons simultaneously (say within ~200 milliseconds of each other), neither registers.

When using this on a phone, that's annoying, as it feels like you should be able to tap both simultaneously.

Tested in Android Firefox 68.11.0 and Android Chrome 84.0.4147.125 on Android 8.0.0 (device is a Samsung Galaxy S7).

**Comment by jperryhouts** [comment]
Thanks. I'll look into it this weekend. Do you happen to know if it worked on a previous Android browser, and has since broken, or if this has always been the case?

**Comment by NateEag** [comment]
I only discovered your nifty project in the past week or two.

This has been true since the day I found it - just finally got around to filing a report.

**Comment by jperryhouts** [comment]
Problem was with listening for click events, which are awkward and slow on mobile. It's fixed by https://github.com/jperryhouts/Dual-N-Back/commit/a8c83ffbc9346f713ac104dcbe5b325fbbfc686b and the changes are live on the website. I have to admit that I personally play this game very rarely anymore, so I never noticed that. Thanks for letting me know!

**Comment by NateEag** [comment]
Working for me. Thanks very much!
