### ISSUE TITLE
Can this project work on Windows Chrome? 

### ISSUE THREAD

**Issue by snehal49** [jperryhouts/Dual-N-Back#3]
I tried running the index.html file using Visual Studio Code (v1.66.2) as I wanted to make edits to test configuration. Got the below error which got resolved by adding the js files as source files.  

Uncaught ReferenceError ReferenceError: start_game is not defined
    at onclick ([c:\Users\.......\index.html:71:45]())

Next, I got this error.
Uncaught DOMException DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at get_screen ([d:\......\js\logic.js:83:62)
    at document.getElementById.onload ([d:\.......\js\logic.js:162:9)
    --- load ---
    at goto_game ([d:\......\js\logic.js:161:49)
    at start_game ([d:\.....\js\logic.js:527:5)
    at onclick ([d:\......\index.html:75:45)

Is there a way to run it on Windows Chrome or am I missing here something? I was able to play the online version on my Windows Chrome browser.  Thanks in advance.

**Comment by jperryhouts** [comment]
It's been a long time since I worked on this code, but I think this is happening because you're trying to load the project directly from your filesystem. I'm guessing the browser objects to javascript requesting something directly from the local filesystem. If that's the case, you need to access it through a web server like Apache.

If you have docker installed, then you should be able to do that with
```
docker run -dit --name dual-n-back -p 8081:80 -v "/path/to/source:/usr/local/apache2/htdocs/" httpd:2.4
```
and then access the app by pointing chrome to `http://localhost:8081/`

Sorry I'm not so familiar with Windows, but I expect it's something like the above. VS code probably has extensions for making that more streamlined.
