### ISSUE TITLE
Apple's mobile browser occasionally fails to play audio

### ISSUE THREAD

**Issue by huoxingyongren** [jperryhouts/Dual-N-Back#6]
When playing the game using the browser that comes with the Apple phone, after a few rounds there is an issue where no audio is playing and the position will be highlighted normally.

**Comment by jperryhouts** [comment]
That's odd, and I don't know exactly what might cause it, but today I did some work on the app including changing the framework that it uses for caching and playing audio. Whatever the issue was, it should be either fixed or replaced with a different issue by now :)

I'm going to close this ticket just to keep things tidy, but please open it back up if you're still experiencing this issue.
